In [1]:
import numpy as np
from algos.naive import naive_search


text = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

pattern = np.array([
    [5,6],
    [8,9]
])


print(naive_search(text, pattern))



text = np.array([
    [1,2],
    [3,4]
])

pattern = np.array([
    [1,2],
    [3,4]
])

print(naive_search(text, pattern))



text = np.array([
    [1,2, 3, 4, 5],
    [3,4, 5, 8, 7]
])

pattern = np.array([
    [5, 6]
])


print(naive_search(text, pattern))




(7, (1, 1))
(4, (0, 0))
(9, None)


In [33]:
np.random.seed(42)
text = np.random.randint(2, size=(10000, 10000))
pattern = np.array([[1, 1, 1, 1, 1],
                    [1, 0, 0, 0, 1],
                    [1, 0, 0, 0, 1],
                    [1, 0, 0, 0, 1],
                    [1, 1, 1, 1, 1]])

res = naive_search(text, pattern)
print(res)
print(text[res[1][0]:res[1][0]+pattern.shape[0], res[1][1]:res[1][1]+pattern.shape[1]])


(38258445, (1913, 6396))
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
